.PHONY: clean All

All:
	@echo "----------Building project:[ random - Debug ]----------"
	@$(MAKE) -f  "random.mk"
clean:
	@echo "----------Cleaning project:[ random - Debug ]----------"
	@$(MAKE) -f  "random.mk" clean
