.PHONY: clean All

All:
	@echo "----------Building project:[ serial_cpp - windowsDebug ]----------"
	@$(MAKE) -f  "serial_cpp.mk"
clean:
	@echo "----------Cleaning project:[ serial_cpp - windowsDebug ]----------"
	@$(MAKE) -f  "serial_cpp.mk" clean
