# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbg676-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib /media/sf_dev/opendev/songpa/songpa.srcs/sources_1/new/keyed_permutation.v
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/sf_dev/opendev/songpa/songpa.cache/wt [current_project]
set_property parent.project_dir /media/sf_dev/opendev/songpa [current_project]
catch { write_hwdef -file keyed_permutation.hwdef }
synth_design -top keyed_permutation -part xc7k70tfbg676-1
write_checkpoint keyed_permutation.dcp
report_utilization -file keyed_permutation_utilization_synth.rpt -pb keyed_permutation_utilization_synth.pb
