.PHONY: clean All

All:
	@echo "----------Building project:[ ftdi - DebugLinux ]----------"
	@$(MAKE) -f  "ftdi.mk"
clean:
	@echo "----------Cleaning project:[ ftdi - DebugLinux ]----------"
	@$(MAKE) -f  "ftdi.mk" clean
